sudo: false
language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
  - git config --global user.name "LexBot"
  - git config --global user.email "jamie.mansfield.jm@outlook.com"
install:
  - ./bukkitc update
  - cd Bukkit-Patches
  - mvn install -DskipTests=true
notifications:
  email: false
env:
  global:
    - LEX_DEPLOY=https://github.com/LexBot/Deploy.git DEPLOY_ROOT=/tmp/lex/deploy
    - GIT_REPO=git@github.com:CanaryBukkitTeam/Repo.git
    - secure: "VU0cpa3X0AvCkjMfs7PH564wOJnKGN0ei0aFlvCxWa7agpMIvEUHAycThcIo6Py/Uv9VhrR2RLdmO0Mbvs3vWDuUicWpg4B1slUlxbwlSGW5mzVNzBGR7BD7XJBoaVqkb9DgDO15kxeCdlhZ77fit8MXHyELy7ALznVJm/2qAUM="
after_success:
  - git clone $LEX_DEPLOY $DEPLOY_ROOT && $DEPLOY_ROOT/maven_repo "mvn source:jar javadoc:jar deploy"
notifications:
  irc: "irc.esper.net#lexteam"

